### ISSUE TITLE
Keep services running after restart

### ISSUE THREAD

**Issue by fatemeh471** [Rapsssito/react-native-background-actions#19]
When the app gets restarted Services are not running؟

**Comment by Rapsssito** [comment]
@fatemeh471, thanks for the feedback! What do you mean by _restarted_? Closing the app deliberately while it is in the background and then opening it?

Could you provide more info about your issue: OS, RN version, etc?

**Comment by fatemeh471** [comment]
@Rapsssito .When I restart the phone, the background service will no longer run in the background.
And we need to open the app to run the services. I don't want to open the app every time
I want the app to always be running after installing the app until we have uninstalled the app

**Comment by fatemeh471** [comment]
When I restart the phone, the background service will no longer run in the
background.
And we need to open the app to run the services. I don't want to open the
app every time
I want the app to always be running after installing the app until we have
uninstalled the app.

I want to always have the app running after installing the app on my phone
until it's always running in the backdrop until I have uninstalled the app.

**Comment by Rapsssito** [comment]
@fatemeh471, sadly that is **not possible** and **out of the scope of this library** since it is not possible to accomplish on iOS. Android, with some tweaking, allows services to be run when the phone restarts. However, iOS does not allow that.
The goal with this library is to offer a consistent way to create and handle a background service in RN so it can be run on Android and iOS in a transparent way.

**Comment by 0anw0** [comment]
What about running those SERVICES with a background fetch library? Is this possible?
