### ISSUE TITLE
null is not an object (evaluating '_RNBackgroundActionsModule.default.start'

### ISSUE THREAD

**Issue by ravithesun02** [Rapsssito/react-native-background-actions#21]
"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-background-actions": "^2.1.0"
  },

error:
[Mon Apr 27 2020 17:22:58.287]  LOG      Trying to start background service
[Mon Apr 27 2020 17:22:58.291]  LOG      Error [TypeError: null is not an object (evaluating '_RNBackgroundActionsModule.default.start')]

**Comment by Rapsssito** [comment]
@ravithesun02, thanks for the feedback! Could you try two things?
* First try with `cd android` and run `./gradlew clean`.
* If it doesn't work try to reinstall your `node_modules`.

**Comment by ravithesun02** [comment]
> @ravithesun02, thanks for the feedback! Could you try two things?
> 
> * First try with `cd android` and run `./gradlew clean`.
> * If it doesn't work try to reinstall your `node_modules`.

I tried both but the error is same

**Comment by Rapsssito** [comment]
@ravithesun02, this problem is related to linking. RN is not able to find the module. It is probably caused by a cache/node_module/pods/metro bad synchronization after the automatic RN linking. I don't know if you are using Expo, but I don't have experience with Expo, so I don't know the exact steps you would follow.

**My advise is to reset/reinstall the library, node_modules folder, metro cache, Gradle cache and pods (and probably de PC).**

I hope it works, reply if the issue still persists.

**Comment by ravithesun02** [comment]
I am not using expo i have created new project and copied your example code to my app.js I am not using expo i have created new project and copied your example code to my app.js

**Comment by Rapsssito** [comment]
@ravithesun02, could you delete `node_modules` and run `yarn install`?

**Comment by ravithesun02** [comment]
Issue is yet the same 
if its possible please go through the code once 
[https://github.com/ravithesun02/sanj ](url)

**Comment by ravithesun02** [comment]
It is fixed . just needed to rebuild the app using Android studio.

**Comment by jakeee51** [comment]
Hey, would like to re-open this issue. Am getting this same error on this library's version 2.6.5
