### ISSUE TITLE
Multiple Task

### ISSUE THREAD

**Issue by PetengDedet** [Rapsssito/react-native-background-actions#51]
Hi, first of all, thank you for this great library. It's straight forward to me. Easy to understand.

Is it possible to run multiple task?

When a task is still running, and not resolved yet, sometimes user want to do another task and just waiting for notification of running tasks to be done.
May be it's like a queue or something. Or even run multiple task with different id at the same time?

I'm considering to use `react-native-queue` but i think it's overkill since it will bring too many resource into my simple app.

Thank you

**Comment by Rapsssito** [comment]
@PetengDedet, **it is not possible to run multiple tasks**. It won't be possible in the near future due to iOS restrictions on background tasks and I want to keep the library's API as much cross-platform friendly as possible.

However, you can turn your "BackgroundTask" into a background task generator (as long as it does not directly affect your UI):
```js
const task = async (taskDataArguments) => {
    await new Promise(() => { // Never resolve
           // Listen to Something1 to start a task
           Something1.addEventListener('event', () => {
              // Starts a new "task"
           };
           // Listen to Something2 to start another task
           Something2.addEventListener('event', () => {
              // Starts a new "task"
           };
    });
};
```

Notice that I have used events as task trigger. You may use whatever method is more convenient for your use case. Hope it helps!

**Comment by PetengDedet** [comment]
I understand what you expect from this library. It's make sense.
Your sample code give me new solution but it's not what i need right now. I changed the app flow. Forcing user to wait until existing task resolved.

Thank you for your answer.

_Closing issue_
