### ISSUE TITLE
Is it possible to hide nofication during sleep()?

### ISSUE THREAD

**Issue by martynasS** [Rapsssito/react-native-background-actions#56]
```
const task = async () => {
	await new Promise(async resolve => {
    	for (let i = 0; BackgroundService.isRunning(); i++) {
		 // doing something

      		await sleep(15 * 60) // hide notification during sleep
    	}
  	});
}
```

**Comment by Rapsssito** [comment]
@martynasS, it is not possible to hide the notification because when you call `sleep()`, the program is still running your background task (listening for the end of sleep event). The only way to hide the notification is to stop the background task.

From Android [documentation](https://developer.android.com/guide/components/foreground-services):
> Each foreground service must show a status bar notification
